// Popular Categories
export const popularCategories = [
  {
    id: "tours",
    name: "Tours",
    image: "/guided-tour-group.png",
  },
  {
    id: "culture",
    name: "Culture",
    image: "/cultural-museum-art.png",
  },
  {
    id: "food",
    name: "Food & Drink",
    image: "/food-tour-culinary-experience.png",
  },
  {
    id: "handcrafting",
    name: "Hand Crafting",
    image: "/placeholder.svg?height=200&width=200&query=handcraft+workshop+pottery+making",
  },
  {
    id: "nature",
    name: "Nature",
    image: "/placeholder.svg?height=200&width=200&query=nature+hike+mountains+forest",
  },
  {
    id: "adventure",
    name: "Adventure",
    image: "/placeholder.svg?height=200&width=200&query=adventure+zipline+rafting+extreme",
  },
]

// Categories
export const allCategories = [
  { id: "all", name: "All Categories" },
  { id: "tours", name: "Tours" },
  { id: "culture", name: "Culture" },
  { id: "food", name: "Food & Drink" },
  { id: "handcrafting", name: "Hand Crafting" },
  { id: "nature", name: "Nature" },
  { id: "adventure", name: "Adventure" },
]

// Featured Experiences
export const featuredExperiences = [
  {
    id: "exp1",
    title: "Guided Tour of the Louvre Museum",
    description:
      "Skip the line and explore the world's most famous museum with an expert guide. See the Mona Lisa, Venus de Milo, and more iconic artworks.",
    location: "Paris, France",
    price: 65,
    rating: 4.8,
    reviews: 1243,
    duration: 3,
    image: "/placeholder.svg?height=300&width=400&query=louvre+museum+paris+mona+lisa",
    category: "culture",
  },
  {
    id: "exp2",
    title: "Sunset Sailing Adventure",
    description: "Experience a breathtaking sunset from the water on this relaxing sailing trip along the coast.",
    location: "Santorini, Greece",
    price: 89,
    rating: 4.9,
    reviews: 876,
    duration: 4,
    image: "/placeholder.svg?height=300&width=400&query=sunset+sailing+santorini+boat",
    category: "adventure",
  },
  {
    id: "exp3",
    title: "Traditional Cooking Class with Local Chef",
    description:
      "Learn to prepare authentic local dishes with fresh ingredients from the market in this hands-on cooking class.",
    location: "Florence, Italy",
    price: 75,
    rating: 4.7,
    reviews: 542,
    duration: 3.5,
    image: "/placeholder.svg?height=300&width=400&query=italian+cooking+class+pasta+making",
    category: "food",
  },
  {
    id: "exp4",
    title: "Jungle Zipline Adventure",
    description:
      "Soar through the rainforest canopy on this thrilling zipline tour with stunning views of the jungle below.",
    location: "Phuket, Thailand",
    price: 55,
    rating: 4.6,
    reviews: 789,
    duration: 2.5,
    image: "/placeholder.svg?height=300&width=400&query=zipline+jungle+adventure+thailand",
    category: "adventure",
  },
  {
    id: "exp5",
    title: "Historical Walking Tour",
    description: "Discover the rich history and hidden stories of the city with a knowledgeable local guide.",
    location: "Prague, Czech Republic",
    price: 25,
    rating: 4.8,
    reviews: 1021,
    duration: 2,
    image: "/placeholder.svg?height=300&width=400&query=prague+old+town+walking+tour",
    category: "tours",
  },
  {
    id: "exp6",
    title: "Desert Safari with BBQ Dinner",
    description: "Experience the thrill of dune bashing followed by a traditional BBQ dinner under the stars.",
    location: "Dubai, UAE",
    price: 95,
    rating: 4.7,
    reviews: 654,
    duration: 6,
    image: "/placeholder.svg?height=300&width=400&query=dubai+desert+safari+dunes+sunset",
    category: "adventure",
  },
  {
    id: "exp7",
    title: "Whale Watching Expedition",
    description: "Set sail on a guided boat tour to observe magnificent whales in their natural habitat.",
    location: "Reykjavik, Iceland",
    price: 85,
    rating: 4.5,
    reviews: 432,
    duration: 3,
    image: "/placeholder.svg?height=300&width=400&query=whale+watching+iceland+humpback",
    category: "nature",
  },
  {
    id: "exp8",
    title: "Wine Tasting Tour",
    description: "Visit local vineyards and sample a variety of fine wines with expert commentary.",
    location: "Napa Valley, USA",
    price: 120,
    rating: 4.9,
    reviews: 876,
    duration: 5,
    image: "/placeholder.svg?height=300&width=400&query=napa+valley+wine+tasting+vineyard",
    category: "food",
  },
  {
    id: "exp9",
    title: "Hot Air Balloon Ride",
    description: "Float gently above the landscape and enjoy breathtaking panoramic views at sunrise.",
    location: "Cappadocia, Turkey",
    price: 175,
    rating: 4.9,
    reviews: 543,
    duration: 3,
    image: "/placeholder.svg?height=300&width=400&query=cappadocia+hot+air+balloons+sunrise",
    category: "adventure",
  },
  {
    id: "exp10",
    title: "Pottery Workshop",
    description: "Learn traditional pottery techniques from master craftsmen in this hands-on workshop.",
    location: "Kyoto, Japan",
    price: 65,
    rating: 4.8,
    reviews: 321,
    duration: 2,
    image: "/placeholder.svg?height=300&width=400&query=japanese+pottery+workshop+traditional",
    category: "handcrafting",
  },
  {
    id: "exp11",
    title: "Street Food Walking Tour",
    description: "Sample the best local street food with a knowledgeable guide who knows all the hidden gems.",
    location: "Bangkok, Thailand",
    price: 45,
    rating: 4.7,
    reviews: 678,
    duration: 3,
    image: "/placeholder.svg?height=300&width=400&query=bangkok+street+food+market+tour",
    category: "food",
  },
  {
    id: "exp12",
    title: "Snorkeling Adventure",
    description: "Explore vibrant coral reefs and swim alongside colorful marine life in crystal clear waters.",
    location: "Great Barrier Reef, Australia",
    price: 110,
    rating: 4.8,
    reviews: 789,
    duration: 4,
    image: "/placeholder.svg?height=300&width=400&query=great+barrier+reef+snorkeling+coral",
    category: "nature",
  },
]

// Top Destinations with high-quality images
export const topDestinations = [
  {
    id: "dest1",
    name: "Paris",
    country: "France",
    description:
      "The City of Light offers iconic landmarks, world-class museums, and charming neighborhoods to explore.",
    image: "/paris-eiffel-tower.png",
    experienceCount: 243,
  },
  {
    id: "dest2",
    name: "Bali",
    country: "Indonesia",
    description: "A tropical paradise with stunning beaches, lush rice terraces, and vibrant cultural experiences.",
    image: "/bali-rice-terraces.png",
    experienceCount: 187,
  },
  {
    id: "dest3",
    name: "Tokyo",
    country: "Japan",
    description: "A fascinating blend of ultramodern and traditional, from neon-lit skyscrapers to historic temples.",
    image: "/tokyo-skyline.png",
    experienceCount: 215,
  },
  {
    id: "dest4",
    name: "Rome",
    country: "Italy",
    description: "The Eternal City is a living museum of ancient history, Renaissance art, and delicious cuisine.",
    image: "/rome-colosseum.png",
    experienceCount: 198,
  },
  {
    id: "dest5",
    name: "New York City",
    country: "USA",
    description: "The Big Apple offers world-famous attractions, diverse neighborhoods, and endless entertainment.",
    image: "/new-york-skyline.png",
    experienceCount: 276,
  },
  {
    id: "dest6",
    name: "Barcelona",
    country: "Spain",
    description: "A vibrant city known for stunning architecture, beautiful beaches, and a lively cultural scene.",
    image: "/barcelona-sagrada-familia.png",
    experienceCount: 167,
  },
]

// Popular Destinations (from previous code)
export const popularDestinations = [
  {
    id: 1,
    name: "Kyoto, Japan",
    location: "Japan",
    image: "/kyoto-temple.png",
    description: "Ancient temples, traditional gardens, and geisha districts in Japan's cultural heart.",
    bestTime: "March-May, Oct-Nov",
    tags: ["Culture", "History"],
  },
  {
    id: 2,
    name: "Santorini",
    location: "Greece",
    image: "/santorini-blue-domes.png",
    description: "Stunning white-washed buildings with blue domes overlooking the Aegean Sea.",
    bestTime: "April-June, Sept-Oct",
    tags: ["Beach", "Romantic"],
  },
  {
    id: 3,
    name: "Barcelona",
    location: "Spain",
    image: "/barcelona-park-guell.png",
    description: "Vibrant city with unique architecture, Mediterranean beaches, and lively culture.",
    bestTime: "May-June, Sept-Oct",
    tags: ["City", "Architecture"],
  },
  {
    id: 4,
    name: "Bali",
    location: "Indonesia",
    image: "/bali-beach-temple.png",
    description: "Tropical paradise with lush rice terraces, sacred temples, and beautiful beaches.",
    bestTime: "April-October",
    tags: ["Beach", "Nature"],
  },
  {
    id: 5,
    name: "New York City",
    location: "USA",
    image: "/new-york-central-park.png",
    description:
      "The city that never sleeps, featuring iconic skyscrapers, diverse neighborhoods, and world-class attractions.",
    bestTime: "April-June, Sept-Nov",
    tags: ["City", "Urban"],
  },
  {
    id: 6,
    name: "Machu Picchu",
    location: "Peru",
    image: "/machu-picchu-ruins.png",
    description: "Ancient Incan citadel set high in the Andes Mountains, offering breathtaking views and rich history.",
    bestTime: "May-September",
    tags: ["Adventure", "History"],
  },
]

// Chat Suggestions (from previous code)
export const chatSuggestions = [
  "Plan a 7-day trip to Italy for a family of four",
  "What are the best beaches in Thailand?",
  "I want to go hiking in national parks in the US",
  "Suggest a romantic weekend getaway in Europe",
  "What should I pack for a trip to Iceland in winter?",
  "Find me budget-friendly destinations in South America",
]
